// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, name)
VALUES (
    gen_random_uuid(), 
    NOW(),
    NOW(),
    $1
)
RETURNING id, created_at, updated_at, name
`

func (q *Queries) CreateUser(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT name FROM users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByName = `-- name: GetUserByName :one
SELECT id FROM users
WHERE name = $1
`

func (q *Queries) GetUserByName(ctx context.Context, name string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getUserByName, name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const purgeUsers = `-- name: PurgeUsers :exec
DELETE FROM users
`

func (q *Queries) PurgeUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, purgeUsers)
	return err
}
